apiVersion: v1
kind: Pod
metadata:
  name: hello-k8s
  namespace: hello-ns
  labels:
    app/name: hello-k8s
    app/component: backend-api
spec:
  containers:
  - name: hellok8scontainer
    image: sonofdarkahmet/hello-k8s
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 5000
